services:
  hapi-fhir-jpaserver-start-1:
    image: harbor.phison.com/fhir/hapi-fhir:${VERSION}
    pull_policy: always
    restart: always
    container_name: hapi-fhir-starter-1
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 16G
        reservations:
          cpus: '8.0'
          memory: 16G
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://192.168.197.214:5434/hapi"
      SPRING_DATASOURCE_USERNAME: "hapipoc"
      SPRING_DATASOURCE_PASSWORD: "hapipoc"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"
    volumes:
      - /term:/term:ro
      - /igs:/app/igs
      - lucene-data:/lucenefiles
    ports:
      - "8080:8080"
    depends_on:
      jaeger:
        condition: service_started
    labels:
      autoheal: true

  hapi-fhir-jpaserver-start-2:
    image: harbor.phison.com/fhir/hapi-fhir:${VERSION}
    pull_policy: always
    restart: always
    container_name: hapi-fhir-starter-2
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 16G
        reservations:
          cpus: '8.0'
          memory: 16G
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://192.168.197.214:5434/hapi"
      SPRING_DATASOURCE_USERNAME: "hapipoc"
      SPRING_DATASOURCE_PASSWORD: "hapipoc"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"
    volumes:
      - /term:/term:ro
      - /igs:/app/igs
      - lucene-data:/lucenefiles
    ports:
      - "8081:8080"
    depends_on:
      jaeger:
        condition: service_started
    labels:
      autoheal: true

  hapi-fhir-jpaserver-start-3:
    image: harbor.phison.com/fhir/hapi-fhir:${VERSION}
    pull_policy: always
    restart: always
    container_name: hapi-fhir-starter-3
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 16G
        reservations:
          cpus: '8.0'
          memory: 16G
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://192.168.197.214:5434/hapi"
      SPRING_DATASOURCE_USERNAME: "hapipoc"
      SPRING_DATASOURCE_PASSWORD: "hapipoc"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"
    volumes:
      - /term:/term:ro
      - /igs:/app/igs
      - lucene-data:/lucenefiles
    ports:
      - "8082:8080"
    depends_on:
      jaeger:
        condition: service_started
    labels:
      autoheal: true

  docker-autoheal:
    image: willfarrell/autoheal
    container_name: docker-autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "14250:14250" # Collector gRPC
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "18080:8080" # cAdvisor's Web UI (optional)
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
volumes:
  lucene-data:
